### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by KajiMaCN** [QuJX/AIS-Visual-Fusion#1]
Thanks for your excellent work!
Could you please share the source code corresponding to this paper?

**Comment by QuJX** [comment]
邮件已收到

**Comment by QuJX** [comment]
In our new work, the anti-occlusion algorithm is updated and integrated into a more accurate version: if the vessel is matched with its AIS, the occluded location will be predicted with the AIS data, if no matching, the location will be predicted via historical visual trajectory (as this paper introduced). The fusion algorithm is also updated to a trajecory-based matching method, which is more accurate. The source code will be avialable after the review of our new paper: 

Guo, Y., Liu, R. W., Qu, J., Lu, Y., Zhu, F., & Lv, Y. (2023). Asynchronous Trajectory Matching-Based Multimodal Maritime Data Fusion for Vessel Traffic Surveillance in Inland Waterways. arXiv preprint arXiv:2302.11283.

For more dataset about vessel detection the simultaneous data about video and AIS data fusion, please see our newest work: https://github.com/gy65896/FVessel, where the source code will be also available after the paper publishment.

**Comment by KajiMaCN** [comment]
> In our new work, the anti-occlusion algorithm is updated and integrated into a more accurate version: if the vessel is matched with its AIS, the occluded location will be predicted with the AIS data, if no matching, the location will be predicted via historical visual trajectory (as this paper introduced). The fusion algorithm is also updated to a trajecory-based matching method, which is more accurate. The source code will be avialable after the review of our new paper:
> 
> Guo, Y., Liu, R. W., Qu, J., Lu, Y., Zhu, F., & Lv, Y. (2023). Asynchronous Trajectory Matching-Based Multimodal Maritime Data Fusion for Vessel Traffic Surveillance in Inland Waterways. arXiv preprint arXiv:2302.11283.
> 
> For more dataset about vessel detection the simultaneous data about video and AIS data fusion, please see our newest work: https://github.com/gy65896/FVessel, where the source code will be also available after the paper publishment.

Thank you!
